### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by nkmrh** [plaidev/karte-ios-sdk#11]
I would love to see support for the swift package manager. Thank you for your support.

**Comment by tikidunpon** [comment]
We are currently considering SwiftPM support. Thanks for the request!

**Comment by tikidunpon** [comment]
@nkmrh 
Would it help your swiftpm use case if we support binary dependency with xcframework (except for KarteCrashReporting)?
or please let us know if you have any specific use case, thank you.

**Comment by nkmrh** [comment]
@tikidunpon  Hi.
I would like to use Swift Package Manager as the only package manager for my project (without using Cocoapods). And I want to install the following products with it.

- KarteCore
- KarteCrashReporting
- KarteInAppMessaging
- KarteRemoteNotification
- KarteVariables
- KarteVisualTracking

Thank you for your consideration.

**Comment by tikidunpon** [comment]
Thanks for the details! 😄 

We will consider the distribution method based on the use cases you provide.
Currently, the SDK contains Swift / Objective-C both, so we plan to provide as binary dependencies.

**Comment by wasnot** [comment]
@nkmrh @nacho4d 
Hello.

We are waiting for you to support Swift package manager.
From the version released last week, I think it's available in Swift Package Manager as version 2.0.0.
However, KarteUtilities is currently closed because it is an internal library.

I hope you can check it.
If you have any problems or comments, please let us know. 

Thank you.

**Comment by nkmrh** [comment]
@wasnot 
Thank you for the support for Swift package manager. I'll use that version from now on. Thank you!
